### PR TITLE
Add parameters to /data/pcds/agg backend endpoint to allow arbitrary lists of selection criteria

### LINKED ISSUE #10: Add parameters to /data/pcds/agg backend endpoint to allow arbitrary lists of selection criteria
The new YNWT Station Data Portal (SDP) uses exactly the same data as PCDS and presents it in almost exactly the same way. Where it differs is in how it selects stations for downloading on the basis of station metadata.

| criterion | PCDS | SDP |
| - | - | - |
| Network | All or single select | arbitrary multi select |
| Variable | fixed groups (e.g., All, Temp (Max.)) | arbitrary multi select |
| Observation Frequency | All or single select | arbitrary multi select |

Data downloads are served via the `/data/pcds/agg` endpoint, which is implemented by the class `pdp_util.agg.PcdsZipApp` in this repo.

The existing API accommodates the PCDS UI. It can easily be extended to accommodate the preferred SDP UI by adding parameters that process lists of network, variable, and observation frequency specifiers. These lists would be comma-separated strings.

The existing API is:

- Method: GET
- URL: `/agg`
- Query parameters:
  * `from-date`: datestring; `< cng.max_obs_time`
  * `to-date`: datestring; `> cng.min_obs_time`
  * `network-name`: string; `== cng.network_name`
  * `input-var`: string; `like cng.vars` (NB: vars must be some aggregate of the variable names?)
  * `input-freq`: string; `== cng.freq`
  * `input-polygon`: string; `ST_intersects(ST_GeomFromText('%s', 4326), the_geom)`
  * `only-with-climatology`: string; `or_(cng.vars.like('%within%'), cng.vars.like('%over%')))` 

The proposed extended API is:

- Method: GET
- URL: `/agg`
- Query parameters:
  * `from-date`: datestring; `< cng.max_obs_time`
  * `to-date`: datestring; `> cng.min_obs_time`
  * `network-name`: string; `== cng.network_name`
  * **`network-names`**: list of network names; `cng.network_name in network-names`
  * `input-var`: string; `like cng.vars` (NB: vars must be some aggregate of the variable names?)
  * **`input-vars`**: list of variable names; `intersection(cng.vars, input-variables) != {}`
  * `input-freq`: string; `== cng.freq`
  * **`input-freqs`**: list of frequencies; `cng.freq in input-freqs`
  * `input-polygon`: string; `ST_intersects(ST_GeomFromText('%s', 4326), the_geom)`
  * `only-with-climatology`: string; `or_(cng.vars.like('%within%'), cng.vars.like('%over%')))`  

Note the 3 new query parameters `network-names`, `input-vars`, `input-freqs`. These are simply plural variations of the existing single-value parameters. The existing query parameters are retained unchanged.

### PR DESCRIPTION
**Pull request by rod-glover**
Resolves #10 

Original API was:

- Method: GET
- URL: `/agg`
- Query parameters:
  * `from-date`: datestring; `< cng.max_obs_time`
  * `to-date`: datestring; `> cng.min_obs_time`
  * `network-name`: string; `== cng.network_name`
  * `input-var`: string; `like cng.vars` (NB: vars must be some aggregate of the variable names?)
  * `input-freq`: string; `== cng.freq`
  * `input-polygon`: string; `ST_intersects(ST_GeomFromText('%s', 4326), the_geom)`
  * `only-with-climatology`: string; `or_(cng.vars.like('%within%'), cng.vars.like('%over%')))` 

Changed API is (changes in bold):

- Method: GET
- URL: `/agg`
- Query parameters:
  * `from-date`: datestring; `< cng.max_obs_time`
  * `to-date`: datestring; `> cng.min_obs_time`
  * **`network-name`**: list of network names; `cng.network_name in network-name`
  * `input-var`: string; `like cng.vars` (NB: vars must be some aggregate of the variable names?)
  * **`input-vars`**: list of variable names; `intersection(cng.vars, input-variables) != {}`
  * **`input-freq`**: list of frequencies; `cng.freq in input-freq`
  * `input-polygon`: string; `ST_intersects(ST_GeomFromText('%s', 4326), the_geom)`
  * `only-with-climatology`: string; `or_(cng.vars.like('%within%'), cng.vars.like('%over%')))`  

Params `network-name` and `input-freq` now accept a list of values instead of a single value. This is backwards compatible with the old API.

New param `input-vars` (plural) accepts a list and behaves slightly differently than `input-var`, which is preserved unchanged for backwards compatibility.

### CODE REVIEW

**Comment by corviday** [comment]
I'm not sure about the big picture context here; can you explain it to me?

I assumed this was updates to the code that handles parsing user queries. But since user queries already support comma-separate lists of variables:

```
lzeman@pcic-2023:~$ curl https://data.pacificclimate.org/data/pcds/lister/raw/EC_raw/1145M29.rsql.ascii?station_observations.air_temperature,station_observations.wind_direction > twind.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  759k    0  759k    0     0   193k      0 --:--:--  0:00:03 --:--:--  193k
lzeman@pcic-2023:~$ curl https://data.pacificclimate.org/data/pcds/lister/raw/EC_raw/1145M29.rsql.ascii?station_observations.wind_direction > t.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  382k    0  382k    0     0   106k      0 --:--:--  0:00:03 --:--:--  106k

lzeman@pcic-2023:~$ ls -lh *.txt
-rw-r--r-- 1 lzeman lzeman 383K Sep 30 11:41 t.txt
-rw-r--r-- 1 lzeman lzeman 760K Sep 30 11:41 twind.txt
```

I am clearly wrong about that! What calls this code?

**Comment by rod-glover** [comment]
The big picture context is in the issue: https://github.com/pacificclimate/pdp_util/issues/10. Here's the info:

The new YNWT Station Data Portal (SDP) uses exactly the same data as PCDS and presents it in almost exactly the same way. Where it differs is in how it selects stations for downloading on the basis of station metadata.

| criterion | PCDS | SDP |
| - | - | - |
| Network | All or single select | arbitrary multi select |
| Variable | fixed groups (e.g., All, Temp (Max.)) | arbitrary multi select |
| Observation Frequency | All or single select | arbitrary multi select |

Data downloads are served via the `/data/pcds/agg` endpoint, which is implemented by the class `pdp_util.agg.PcdsZipApp` in this repo.

The existing API accommodates the PCDS UI. It can easily be extended to accommodate the preferred SDP UI by adding parameters that process lists of network, variable, and observation frequency specifiers. These lists would be comma-separated strings.

**Comment by rod-glover** [comment]
This code is called by the PCDS backend app; it is the meat of that backend after the relatively trivial URL routing. (Its client is the PCDS frontend app.) It streams the data requested when a user clicks the Download or Timeseries button on the PCDS frontend.

**Comment by corviday** [comment]
A user can already download multiple variables, so I'm having trouble figuring out when one would use the new `input-vars` parameter or what it does differently.

**Comment by rod-glover** [comment]
I think several things are relevant here:

1. This revised interface is for the new YNWT Station Data Portal (SDP). Its UI allows arbitrary selections of any combination of variables, any combination of networks, and any combination of observation frequencies. Instead of building an entirely new API, the needs of both can easily be accommodated by this relatively small modification to the existing API.

1. The existing PCDS app allows a more limited selection of variables (only one category, e.g., temperature) at a time, and only one network and only one observation frequency. This is insufficient to support the new UI offered by SDP.

1. The consequence of specifying variables, network(s), and frequency(ies) is to select a set of stations which match these criteria. When the user clicks Download Climatology or Download Timeseries, the backend computes this station set, then streams the data from each station in turn and aggregates (hence the API endpoint name `/agg`) the result as a single zip file with one file for each station. It is the station selection computation that needs modifying (and the API to go with it).

That all said, it may be that the "stream the data for each station" needs some attention too, in the department of variable specification. I will look into this. Meantime, please continue to ask questions if this still doesn't make it clear what this PR is for.

**Comment by corviday** [comment]
> That all said, it may be that the "stream the data for each station" needs some attention too, in the department of variable specification. I will look into this. Meantime, please continue to ask questions if this still doesn't make it clear what this PR is for.

I don't think there's any reason to suspect "stream the data from each station" needs attention; users can already stream multiple variables, which has been the root of my confusion the whole time!

Okay, so to confirm: this PR doesn't affect user data download at all. Instead, it affects the `/agg` endpoint, which is never called explicitly (ie, you never see `agg` in a url), but is what handles the two URLs I pasted above?

**Comment by rod-glover** [comment]
I think you may be mistaken about the data download URLs.

When the user clicks a download button, the `/agg` endpoint is called. I just did this, and the URL is 
```
https://data.pacificclimate.org/data/pcds/agg/?from-date=1870%2F01%2F01&to-date=2019%2F09%2F30&input-polygon=&input-var=&network-name=&input-freq=&data-format=nc&download-climatology=Climatology
```

Not the `/agg` at the end of the path portion.

The URLs you posted (`count_stations`, `record_length`) are summary metadata URLs. They do not respond with station data (observations), they respond with some descriptive information. They are not my concern here, or at all. I think this may be where the confusion lies.

**Comment by rod-glover** [comment]
Finally, my investigations indicate that the station data streamed by the `/agg` endpoint is not constrained by the variable selection. All variables available for a station are streamed. The variable criterion only determines which stations are selected for downloading.

**Comment by corviday** [comment]
Ah... the confusion is actually that we apparently have _two_ completely unrelated sets of APIs for data download, and we've each been talking about a different one this entire time. My first comment contains a set of data download urls using `/lister` that download data for multiple variables (one of the URLs is tasmax only, the other is tasmax and wind).

So when you said `/agg` was responsible for streaming the data a user requested, I was a bit lost.

**Comment by rod-glover** [comment]
Yeah. 

I'm not sure that `/lister` is still used: Whereas there is a URL involving `/agg` computed in the CRMP (PCDS) app, there is nothing involving `/lister`. I also never see `/lister` in the traces of network usage in the browser when I download a file. Not sure what the deal is here.

**Comment by corviday** [comment]
`/lister` is the OpENDAP interface. I assumed the front end was using it, but I guess not!

**Comment by rod-glover** [comment]
Of course; `/agg` calls `/lister` behind the scenes. Well spotted.

**Comment by rod-glover** [comment]
:relieved: 

Thanks for your diligence. It's really important not to mess this backend up.

**Comment by rod-glover** [comment]
Just realized that the method used to compare the list of `input-vars` to a station's variable list reduces to the method used for `input-var` for a single variable (and for the empty string). So this could be accommodated, like `network-name` and `input-freq`, by a simple extension to how `input-var` functions.

**Comment by rod-glover** [comment]
# New backend API tests

Running PCDS on dev machine with new backend. Trial downloads of data.

## PCDS style downloads

### One station

`http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F02&input-polygon=MULTIPOLYGON%28%28%28-122.67117151975867+52.42516378639454%2C-122.53605574484632+51.664086544404725%2C-121.4547948744784+52.16460650205663%2C-122.67117151975867+52.42516378639454%29%29%29&input-var=air_temperature_mean&network-name=ENV-AQN&input-freq=1-hourly&data-format=nc&download-timeseries=Timeseries`

Result matches download from prod

## SDP style downloads

### Specifying networks

Location: North of Alexandria.

Polygon selects 4 stations (without network constraint), one from each of the following networks:
- EC_raw
- ENV-AQN
- FLNRO-WMB
- MoTIe

Unmodified request URL:
`
http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F03&input-polygon=MULTIPOLYGON%28%28%28-122.67971677545394+53.10987194851064%2C-122.64369896890715+52.83012199592006%2C-121.7223225072985+52.874852888131656%2C-122.67971677545394+53.10987194851064%29%29%29&input-var=&network-name=&input-freq=&data-format=nc&cliptodate=cliptodate&download-climatology=Climatology
`

#### Test 1
Specify 2 of 4 networks with `network-name=EC_raw,MoTIe`. In combination with polygon, this selects 2 of 4 stations.

Modified request URL:
`
http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F03&input-polygon=MULTIPOLYGON%28%28%28-122.67971677545394+53.10987194851064%2C-122.64369896890715+52.83012199592006%2C-121.7223225072985+52.874852888131656%2C-122.67971677545394+53.10987194851064%29%29%29&input-var=&network-name=EC_raw,MoTIe&input-freq=&data-format=nc&cliptodate=cliptodate&download-climatology=Climatology
`

Downloads the expected 2 of 4 stations.

### Specifying observation frequencies

Location: Penticton area.

Polygon selects 3 stations (without frequency constraint), one from each of the following networks:
- EC_raw
- FLNRO-WMB
- MoTIe

Frequencies:
- Hourly (FLNRO-WMB, MoTIe)
- Daily (EC_raw)

Unmodified request URL:
`
http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F03&input-polygon=MULTIPOLYGON%28%28%28-119.65576269684227+49.61013247430256%2C-119.49898147676022+49.520686151674596%2C-119.9718531664976+49.357707253426945%2C-119.65576269684227+49.61013247430256%29%29%29&input-var=&network-name=&input-freq=&data-format=nc&cliptodate=cliptodate&download-climatology=Climatology
`

#### Test 1

Specify 1 of 3 networks with `input-freq=hourly,daily`. In combination with polygon, this selects 1 station, since `hourly` is not valid (should be `1-hourly`).

Modified request URL:
`
http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F03&input-polygon=MULTIPOLYGON%28%28%28-119.65576269684227+49.61013247430256%2C-119.49898147676022+49.520686151674596%2C-119.9718531664976+49.357707253426945%2C-119.65576269684227+49.61013247430256%29%29%29&input-var=&network-name=&input-freq=hourly,daily&data-format=nc&cliptodate=cliptodate&download-climatology=Climatology
`

Downloads only the daily station (network EC_raw). Correct.

#### Test 2


Specify 3 of 3 networks with `input-freq=1-hourly,daily`. In combination with polygon, this selects all 3 stations.

Modified request URL:
`
http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F03&input-polygon=MULTIPOLYGON%28%28%28-119.65576269684227+49.61013247430256%2C-119.49898147676022+49.520686151674596%2C-119.9718531664976+49.357707253426945%2C-119.65576269684227+49.61013247430256%29%29%29&input-var=&network-name=&input-freq=1-hourly,daily&data-format=nc&cliptodate=cliptodate&download-climatology=Climatology
`

Downloads stations for all 3 networks. Correct.

### Specifying variables

Location: Fort St John area N to Rose Prairie

Polygon selects 5 stations in the following networks:
- ENV-AQN
- FLNRO-WMB
- MoTIe 

Variables (PCDS selector):
- Precipitation Amount (FLNRO-WMB, MoTIe ): `lwe_thickness_of_precipitation_amount_sum`
- Temperature (Mean) (ENV-AQN): `air_temperature_mean`

Unmodified request URL:
`
http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F03&input-polygon=MULTIPOLYGON%28%28%28-121.4910309395485+56.65825274563535%2C-121.59596682182368+56.13401244529504%2C-120.37378399301832+56.030936234694494%2C-120.1251200199123+56.61812322854423%2C-121.4910309395485+56.65825274563535%29%29%29&input-var=&network-name=&input-freq=&data-format=nc&cliptodate=cliptodate&download-climatology=Climatology
`

Downloads stations for the 3 networks

#### Test 1

Download all stations by selecting both variables

Modified request URL:
`
http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F03&input-polygon=MULTIPOLYGON%28%28%28-121.4910309395485+56.65825274563535%2C-121.59596682182368+56.13401244529504%2C-120.37378399301832+56.030936234694494%2C-120.1251200199123+56.61812322854423%2C-121.4910309395485+56.65825274563535%29%29%29&input-vars=lwe_thickness_of_precipitation_amount_sum,air_temperature_mean&network-name=&input-freq=&data-format=nc&cliptodate=cliptodate&download-climatology=Climatology
`

Downloaded 3 networks. Correct.

#### Test 2

Download only ENV-AQN network stations by selecting variable `air_temperature_mean`

Modified request URL:
`
http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F03&input-polygon=MULTIPOLYGON%28%28%28-121.4910309395485+56.65825274563535%2C-121.59596682182368+56.13401244529504%2C-120.37378399301832+56.030936234694494%2C-120.1251200199123+56.61812322854423%2C-121.4910309395485+56.65825274563535%29%29%29&input-vars=air_temperature_mean&network-name=&input-freq=&data-format=nc&cliptodate=cliptodate&download-climatology=Climatology
`

Downloaded only ENV-AQN stations. Correct.

#### Test 2

Download only FLNRO-WMB, MoTIe network stations by selecting variable `lwe_thickness_of_precipitation_amount_sum`

Modified request URL:
`
http://127.0.0.1:8000/data/pcds/agg/?from-date=2019%2F09%2F25&to-date=2019%2F10%2F03&input-polygon=MULTIPOLYGON%28%28%28-121.4910309395485+56.65825274563535%2C-121.59596682182368+56.13401244529504%2C-120.37378399301832+56.030936234694494%2C-120.1251200199123+56.61812322854423%2C-121.4910309395485+56.65825274563535%29%29%29&input-vars=lwe_thickness_of_precipitation_amount_sum&network-name=&input-freq=&data-format=nc&cliptodate=cliptodate&download-climatology=Climatology
`

Downloaded only FLNRO-WMB, MoTIe network stations. Correct.

**Comment by rod-glover** [comment]
The above tests are not comprehensive, but cover many cases. Together with unit tests, they strongly suggest that this modification is working as intended.

**Comment by rod-glover** [comment]
A considerably extended test suite, like the one above, has been completed. Trust Me<sup>TM</sup>.

**Pull request merged**
